// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuZRFBvU5J18caIQ4_4uCtr9qyv3elEg4',
    appId: '1:636631667334:web:9c742737a75dc09a257707',
    messagingSenderId: '636631667334',
    projectId: 'histomepweb-1da8a',
    authDomain: 'histomepweb-1da8a.firebaseapp.com',
    databaseURL: 'https://histomepweb-1da8a-default-rtdb.firebaseio.com',
    storageBucket: 'histomepweb-1da8a.appspot.com',
    measurementId: 'G-85M55XBC0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpFqe7jv32q2y151zA79_nbWCgl7rMzvw',
    appId: '1:636631667334:android:3abf5a6ec0f3b4b5257707',
    messagingSenderId: '636631667334',
    projectId: 'histomepweb-1da8a',
    databaseURL: 'https://histomepweb-1da8a-default-rtdb.firebaseio.com',
    storageBucket: 'histomepweb-1da8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6T_84RBEuJ6aq8A8p_3AHHPS9eZrEpf8',
    appId: '1:636631667334:ios:8893fe285f79870f257707',
    messagingSenderId: '636631667334',
    projectId: 'histomepweb-1da8a',
    databaseURL: 'https://histomepweb-1da8a-default-rtdb.firebaseio.com',
    storageBucket: 'histomepweb-1da8a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6T_84RBEuJ6aq8A8p_3AHHPS9eZrEpf8',
    appId: '1:636631667334:ios:8893fe285f79870f257707',
    messagingSenderId: '636631667334',
    projectId: 'histomepweb-1da8a',
    databaseURL: 'https://histomepweb-1da8a-default-rtdb.firebaseio.com',
    storageBucket: 'histomepweb-1da8a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuZRFBvU5J18caIQ4_4uCtr9qyv3elEg4',
    appId: '1:636631667334:web:f096ecc243d9410b257707',
    messagingSenderId: '636631667334',
    projectId: 'histomepweb-1da8a',
    authDomain: 'histomepweb-1da8a.firebaseapp.com',
    databaseURL: 'https://histomepweb-1da8a-default-rtdb.firebaseio.com',
    storageBucket: 'histomepweb-1da8a.appspot.com',
    measurementId: 'G-KQHHB5DMGS',
  );
}
